<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mochibot_bringup</name>
  <version>0.0.0</version>
  <description>Bringup package for MochiBot</description>
  <maintainer email="rog-ubundu@todo.todo">rog-ubundu</maintainer>
  <license>Apache-2.0</license>
  <depend>rclcpp</depend>
  <depend>mochibot_description</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
